#!/bin/sh
cargo build
cargo test
# Note: --fail-under-lines is not used because the lint code runs in a subprocess
# (dylint driver) and its coverage cannot be captured by cargo-llvm-cov.
cargo llvm-cov
